version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: resume-crafter-db
    environment:
      POSTGRES_DB: resume_crafter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: